# skeleton list
synapse_admin_skeleton_list:
    path: /
    defaults:
        _controller: "SynapseAdminBundle:SkeletonAdmin:list"

# skeleton init
synapse_admin_skeleton_init:
    path: /create
    defaults:
        _controller: "SynapseAdminBundle:SkeletonAdmin:init"
    methods:
        - GET
        - POST

# skeleton edition
synapse_admin_skeleton_edition:
    path: /{id}/edit
    defaults:
        _controller: "SynapseAdminBundle:SkeletonAdmin:edit"
    methods:
        - GET
        - POST
    requirements:
        id: \d+
